"use client";

import { useEffect, useState } from "react";
// import { API } from "aws-amplify";
// import { listServiceRequests } from "@/graphql/queries"; // Generated by Amplify
import { AgGridReact } from "ag-grid-react";
import "ag-grid-community/styles/ag-grid.css";
import "ag-grid-community/styles/ag-theme-alpine.css";

export default function ServiceRequestTable() {
  const [rowData, setRowData] = useState([]);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      // const result = await API.graphql({ query: listServiceRequests });
      // setRowData(result.data.listServiceRequests.items);
    } catch (error) {
      console.error("Error fetching data:", error);
    }
  };

  const columnDefs = [
    { field: "caseNumber", headerName: "Case Number" },
    { field: "serviceRequestName", headerName: "Name" },
    { field: "serviceRequestDescription", headerName: "Description" },
    { field: "creationDate", headerName: "Creation Date" },
    { field: "severity", headerName: "Severity" },
    { field: "resolutionDate", headerName: "Resolution Date" },
    { field: "reporterName", headerName: "Reporter Name" },
    { field: "contactInformation", headerName: "Contact Information" },
    { field: "location", headerName: "Location" },
  ];

  return (
    <div className="ag-theme-alpine" style={{ height: 400, width: "100%" }}>
      {/* <AgGridReact rowData={rowData} columnDefs={columnDefs} /> */}
    </div>
  );
}